// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHlTv1TBXiecI1jQXEF_DIG9KtKHtfJUw',
    appId: '1:208641194395:web:81f8f5ca1e69be593ec93e',
    messagingSenderId: '208641194395',
    projectId: 'vetjirani-3da7c',
    authDomain: 'vetjirani-3da7c.firebaseapp.com',
    storageBucket: 'vetjirani-3da7c.firebasestorage.app',
    measurementId: 'G-628WW99EZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm5w-NmdXU2t_k_BdEDUsOWw3KGGOQg3I',
    appId: '1:208641194395:android:7d1b7cb6780d52e03ec93e',
    messagingSenderId: '208641194395',
    projectId: 'vetjirani-3da7c',
    storageBucket: 'vetjirani-3da7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFAJecv4a39DLOiBFjd54ocQL7J_htZzw',
    appId: '1:208641194395:ios:5522c538f3b725243ec93e',
    messagingSenderId: '208641194395',
    projectId: 'vetjirani-3da7c',
    storageBucket: 'vetjirani-3da7c.firebasestorage.app',
    androidClientId: '208641194395-h3n3pfpvtbejjtvd2tntt1lk7odjkp06.apps.googleusercontent.com',
    iosClientId: '208641194395-sg9fuglgasllpbssut82v701m8632htt.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetjiraniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFAJecv4a39DLOiBFjd54ocQL7J_htZzw',
    appId: '1:208641194395:ios:5522c538f3b725243ec93e',
    messagingSenderId: '208641194395',
    projectId: 'vetjirani-3da7c',
    storageBucket: 'vetjirani-3da7c.firebasestorage.app',
    androidClientId: '208641194395-h3n3pfpvtbejjtvd2tntt1lk7odjkp06.apps.googleusercontent.com',
    iosClientId: '208641194395-sg9fuglgasllpbssut82v701m8632htt.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetjiraniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHlTv1TBXiecI1jQXEF_DIG9KtKHtfJUw',
    appId: '1:208641194395:web:2a2bddd71d1f95f33ec93e',
    messagingSenderId: '208641194395',
    projectId: 'vetjirani-3da7c',
    authDomain: 'vetjirani-3da7c.firebaseapp.com',
    storageBucket: 'vetjirani-3da7c.firebasestorage.app',
    measurementId: 'G-J229HKVW9Z',
  );
}
